version: '3.8'
services:
  app:
    image: social_forecaster
    build: .
    ports:
      - "8000:8000"
    environment:
      - NEWS_API_KEY=${NEWS_API_KEY}
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
